version: '2'
services:
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        ports:
            - 8000:80
            - 443:443
        environment:
            - PROJECT_DOMAIN=domain.local
            - PROJECT_WEB_DIR=/home/docker/build
            - PROJECT_WEB_INDEX=index.html
            - APACHE_LOG_DIR=/var/log/apache2
        volumes:
            - logs:/var/log/apache2
        volumes_from:
            - project
        depends_on:
            - project

    project:
        build:
            context: .
            dockerfile: ./docker/project/Dockerfile
        volumes:
            - ./:/home/docker

    elk:
        image: willdurand/elk:latest
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./docker/logstash:/etc/logstash
        volumes_from:
            - elk-data
            - web
        depends_on:
            - web
            - elk-data

    elk-data:
        image: busybox:latest
        tty: true
        volumes:
            - data:/data

volumes:
    logs: {}
    data: {}

